# Generated by Django 4.1.7 on 2023-04-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        ('articles', '0004_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='comments',
            field=models.ManyToManyField(related_name='article_comments', to='comments.comment'),
        ),
    ]
