apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
        - name: django-app
          image: amithreddy06/final-app:latest  # Replace with your Docker image
          ports:
            - containerPort: 8000  # Assuming your Django app runs on port 8000
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: "Blog.settings"  # Replace with your Django settings module
          volumeMounts:
            - name: sqlite-storage
              mountPath: /app/db  # Mount path for SQLite database file
      volumes:
        - name: sqlite-storage
          persistentVolumeClaim:
            claimName: sqlite-storage
